version: '3.8'

services:
  mcp_server:
    build:
      context: . # Build context is the root directory
      dockerfile: src/mcp_server/Dockerfile # Specify Dockerfile location
    env_file:
      - .env # Load environment variables from .env file
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src # Mount the src directory for live code changes
      - ./config:/app/config # Mount config directory
      - ./.lean:/root/.lean  # Store LEAN CLI config
    depends_on:
      - lean_engine # Ensure lean_engine starts first
    environment:
      - QC_USER_ID=${QC_USER_ID}
      - QC_API_TOKEN=${QC_API_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ALLOWED_SYMBOLS=${ALLOWED_SYMBOLS}
      - QC_PROJECTS_DIR=${QC_PROJECTS_DIR}

  lean_engine:
    image: quantconnect/lean:latest
    volumes:
      - ./src/strategies:/Lean/Strategies # Mount strategies directory
      - ./data:/Lean/Data # Mount data directory
    environment:
      - QC_USER_ID=${QC_USER_ID}
      - QC_API_TOKEN=${QC_API_TOKEN}